upgrade-installed-packages: limit macOS-only `brew upgrade` to `--cask`
Common `brew upgrade --greedy` for Linux and macOS isn’t possible
because `brew upgrade` on Linux automatically specified `--formula`,
which is incompatible with `--greedy`:

    Error: Invalid usage: Options --formula and --greedy are mutually exclusive.